backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
 - name: "questions"
   label: "Questions"
   folder: "content/questions"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Categories", name: "categories", widget: "string", required: true}
    - {label: Type, name: type, widget: hidden, default: post}

 - name: "bible_verses"
   label: "Bible Verses"
   folder: "content/bible_verses"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Categories", name: "categories", widget: "string", required: true}
    - {label: Type, name: type, widget: hidden, default: post}