backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
 - name: "pages"
   label: "Pages"
   files:
    - label: "About Page"
      name: "about"
      file: "content/about.md"
      fields:
        - {label: "Title", name: "title", widget: "string", required: true}
        - {label: "Content", name: "body", widget: "markdown", required: true}
    - label: "Contact Page"
      name: "contact"
      file: "content/contact.md"
      fields:
        - {label: "Title", name: "title", widget: "string", required: true}
    - label: "Privacy Page"
      name: "privacy"
      file: "content/privacy.md"
      fields:
        - {label: "Title", name: "title", widget: "string", required: true}
        - {label: "Content", name: "body", widget: "markdown", required: true}
 - name: "questions"
   label: "Questions"
   folder: "content/questions"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
    - {label: "Categories", name: "categories", widget: "select", options: ["share", "encourage", "explain", "deepen"], required: true}
    - {label: Type, name: type, widget: hidden, default: "questions"}
    - {label: "Content", name: "body", widget: "markdown", required: true}

 - name: "bible_verses"
   label: "Bible Verses"
   folder: "content/bible_verses"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
    - {label: "Categories", name: "categories", widget: "select", options: ["share", "encourage", "explain", "deepen", "youth-group"], required: true}
    - {label: Type, name: type, widget: hidden, default: "bible_verses"}
    - {labe: "Version", name: "version", widget: "text", required: true}
    - {label: "Content", name: "body", widget: "markdown", required: true}
  
 - name: "testimonies"
   label: "Testimonies"
   folder: "content/testimonies"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
    - {label: "Categories", name: "categories", widget: "select", options: ["share", "encourage", "explain", "deepen", "youth-group"], required: true}
    - {label: Type, name: type, widget: hidden, default: "testimonies"}
    - {label: "Header Image", name: "image", widget: image, default: "uploads/church.jpg", required: false, allow_multiple: false}
    - {label: "Content", name: "body", widget: "markdown", required: true}
 
 - name: "articles"
   label: "Articles"
   folder: "content/articles"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
    - {label: "Categories", name: "categories", widget: "select", options: ["share", "encourage", "explain", "deepen", "youth-group"], required: true}
    - {label: Type, name: type, widget: hidden, default: "articles"}
    - {label: "Header Image", name: "image", widget: image, default: "uploads/book.jpg", required: false, allow_multiple: false}
    - {label: "Text Content", name: "body", widget: "markdown", required: true}
    - {label: "URL", name: "link", widget: "string", required: false}

 - name: "songs"
   label: "Songs"
   folder: "content/songs"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Layout", name: "layout", widget: "hidden", default: "song"}
    - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
    - {label: "Categories", name: "categories", widget: "select", options: ["share", "encourage", "explain", "deepen", "youth-group"], required: true}
    - {label: Type, name: type, widget: hidden, default: "songs"}
    - {label: "URL", name: "link", widget: "string", required: true}
    - {label: "Lyrics URL", name: "lyrics", widget: "string", required: false}

 - name: "videos"
   label: "Videos"
   folder: "content/videos"
   create: true
   slug: "{{slug}}"
   fields:
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
    - {label: "Categories", name: "categories", widget: "select", options: ["share", "encourage", "explain", "deepen", "youth-group"], required: true}
    - {label: Type, name: type, widget: hidden, default: "videos"}
    - {label: "YOUTUBE", name: "link", widget: youtube, extraInfo: true, required: true}
